INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST123',
    'ES',
    'ES',
    'ENT001',
    'Y'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST123',
    'MX',
    'MX',
    'ENT001',
    'Y'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST987',
    'US',
    'US',
    'ENT002',
    'N'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST987',
    'MX',
    'MX',
    'ENT002',
    'Y'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST456',
    'FR',
    'FR',
    'ENT003',
    'S'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST456',
    'MX',
    'MX',
    'ENT003',
    'N'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER_NATIONALITIES (
    G_CUSTOMER_ID,
    G_COUNTRY_NATIONALITY_ID,
    G_COUNTRY_ID,
    G_ENTITY_ID,
    G_MAIN_NATIONALITY_IND_TYPE
) VALUES (
    'CUST321',
    'MX',
    'MX',
    'ENT003',
    'N'
);

INSERT INTO KBTQ.T_KBTQ_CUSTOMER (G_CUSTOMER_ID, G_COUNTRY_ID, GF_ENTITY_ID, GF_CUSTOMER_ID, GF_TAXPAYER_ID, GF_COUNTRY_NATIONALITY_ID)
VALUES ('CUST123', 'ES', 'ENT1', 'CUST123', 'TAX001', 'ESP');

INSERT INTO KBTQ.T_KBTQ_CUSTOMER (G_CUSTOMER_ID, G_COUNTRY_ID, GF_ENTITY_ID, GF_CUSTOMER_ID, GF_TAXPAYER_ID)
VALUES ('CUST987', 'US', 'ENT2', 'CUST987', 'TAX002');

INSERT INTO KBTQ.T_KBTQ_CUSTOMER (G_CUSTOMER_ID, G_COUNTRY_ID, GF_ENTITY_ID, GF_CUSTOMER_ID, GF_TAXPAYER_ID)
VALUES ('CUST456', 'MX', 'ENT3', 'CUST456', 'TAX003');

INSERT INTO KBTQ.T_KBTQ_CUSTOMER (G_CUSTOMER_ID, G_COUNTRY_ID, GF_ENTITY_ID, GF_CUSTOMER_ID, GF_TAXPAYER_ID)
VALUES ('CUST321', 'MX', 'ENT4', 'CUST321', 'TAX004');