INSERT INTO KUSU.T_KUSU_CUST_USER_PROFILE (G_USER_ACCOUNT_ID, G_USER_ID, G_ROLE_PERSON_ID)
VALUES ('ACC1', 'USER1', 'CUST1');

INSERT INTO KUSU.T_KUSU_CUST_USER_PROFILE (G_USER_ACCOUNT_ID, G_USER_ID, G_ROLE_PERSON_ID)
VALUES ('ACC2', 'USER2', 'CUST2');

INSERT INTO KUSU.T_KUSU_CUST_USER_PROFILE (G_USER_ACCOUNT_ID, G_USER_ID, G_ROLE_PERSON_ID)
VALUES ('ACC3', 'USER3', 'CUST3');


INSERT INTO KUSU.T_KUSU_USER (G_USER_ID, GF_PERSONAL_ID)
VALUES ('USER1', 'DOCUM1');

INSERT INTO KUSU.T_KUSU_USER (G_USER_ID, GF_PERSONAL_ID)
VALUES ('USER2', 'DOCUM2');

INSERT INTO KUSU.T_KUSU_USER (G_USER_ID, GF_PERSONAL_ID)
VALUES ('USER3', 'DOCUM3');